name: Minha Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  teste:

    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar pytest
        run: pip install pytest

      - name: Rodar testes
        run: pytest